export enum Role {
  ADMIN = 'admin',
  CUSTOMER = 'customer',
  USER = 'user',
  SYSTEM = 'system',
}

export enum OrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAYMENT_SUBMITTED = 'PAYMENT_SUBMITTED',
  PAID_CONFIRMED = 'PAID_CONFIRMED',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentStatus {
  PENDING_SUBMISSION = 'PENDING_SUBMISSION',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum GrowthState {
  GERMINATING = 'GERMINATING',
  HEALTHY_VEGETATIVE = 'HEALTHY_VEGETATIVE',
  OVERWATERED_STUNTED = 'OVERWATERED_STUNTED',
  UNDERWATERED_WILTING = 'UNDERWATERED_WILTING',
  NITROGEN_DEFICIENT_CHLOROSIS = 'NITROGEN_DEFICIENT_CHLOROSIS',
  NUTRIENT_BURN = 'NUTRIENT_BURN',
  LIGHT_STARVED_ETIOLATED = 'LIGHT_STARVED_ETIOLATED',
  HEALTHY_FLOWERING = 'HEALTHY_FLOWERING',
  READY_FOR_HARVEST = 'READY_FOR_HARVEST',
  DEAD = 'DEAD',
}
